import type { Metadata } from "next";

import { inter } from "./fonts";
import "./globals.css";
import HomeTemplate from "./commons/components/templates/home.template";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-body-default antialiased`}>
        <HomeTemplate> {children}</HomeTemplate>
      </body>
    </html>
  );
}
