import type { Metadata } from "next";

import { inter } from "./fonts";
import "./globals.css";
import HomeTemplate from "./commons/components/templates/home.template";
import CartProvider from "./_modules/products/infrastructure/context/carts.context";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-body-default antialiased`}>
        <CartProvider>
          <HomeTemplate> {children}</HomeTemplate>
        </CartProvider>
      </body>
    </html>
  );
}
